//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularCsharp.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AngularCsharp.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {{firstName}}!.
        /// </summary>
        internal static string simple1_html {
            get {
                return ResourceManager.GetString("simple1_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///    &lt;title&gt;Reminder Mail Dessertkarten: Offene Gut-zum-Druck Auftr�ge - �bersicht&lt;/title&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: &apos;Segoe UI&apos;, &apos;Segoe&apos;, &apos;SegoeUI-Regular-final&apos;, Tahoma, Geneva, Verdana, Helvetica, Arial, s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usecase1_html {
            get {
                return ResourceManager.GetString("usecase1_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;salesAgent&quot;: {
        ///    &quot;SalesAgentPkId&quot;: 1001,
        ///    &quot;EmailTypeId&quot;: 1001,
        ///    &quot;EmailFrequencyId&quot;: 1001,
        ///    &quot;SalesAgentRegionId&quot;: 1004,
        ///    &quot;NestleAgentNo&quot;: &quot;329&quot;,
        ///    &quot;FirstName&quot;: &quot;Marc&quot;,
        ///    &quot;LastName&quot;: &quot;Aeschlimann&quot;,
        ///    &quot;EmailAddress&quot;: &quot;Marc.Aeschlimann@ch.nestle.com&quot;,
        ///    &quot;PhoneNumber&quot;: &quot; + 41 79 778 13 26&quot;,
        ///    &quot;LanguageId&quot;: 1010,
        ///    &quot;Comment&quot;: null,
        ///    &quot;IsActive&quot;: true,
        ///    &quot;FullName&quot;: &quot;Marc Aeschlimann&quot;,
        ///    &quot;EmailFrequency&quot;: null,
        ///    &quot;EmailType&quot;: null,
        ///    &quot;SalesAgentRegion&quot;: nul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usecase1_json {
            get {
                return ResourceManager.GetString("usecase1_json", resourceCulture);
            }
        }
    }
}
